version: "3.7"

networks:
  bookie:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookie
      MYSQL_USER: root
      MYSQL_PASSWORD: Development!!
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - bookie
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: Development!!
      DB_DATABASE: bookie
    depends_on:
      - mysql
    command: pnpm dev
    ports:
      - "4000:4000"
    networks:
      - bookie

volumes:
  mysql:
